# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=
endif
export config

PROJECTS := towerdefense jsonParserTest

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

towerdefense: 
	@echo "==== Building towerdefense ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f towerdefense.make

jsonParserTest: 
	@echo "==== Building jsonParserTest ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f jsonParserTest.make

clean:
	@${MAKE} --no-print-directory -C . -f towerdefense.make clean
	@${MAKE} --no-print-directory -C . -f jsonParserTest.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   "
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   towerdefense"
	@echo "   jsonParserTest"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
